server:
  port:8071

spring:
  mysql:
    console:
      enabled:true


keycloak:
  realm: Contact
  auth-server-url: http://localhost:8180/auth
  resource: microservice
  public-client: true
  bearer-only: true
